version: "3"

services:
  postgres:
    image: postgres
    tty: true
    container_name: postgre_test
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pizza
      - POSTGRES_HOST_AUTH_METHOD=trust
  pizza:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
        - "8080:8080"
    depends_on:
      - postgres